# Generated by Django 4.2.10 on 2024-02-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('release_year', models.PositiveBigIntegerField()),
                ('image', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
    ]
